#name: Run Automation Framework (Windows)

#on:
#  schedule:
#    - cron: '30 3 * * *'  # 9 AM IST (IST = UTC +5:30)
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
 #     - master
#
